parameters:
    imi_borbas_video_gallery.video_importer_factory.class: ImiBorbas\VideoGalleryBundle\Importing\DefaultVideoImporterFactory
    imi_borbas_video_gallery.video_gallery_updater.class: ImiBorbas\VideoGalleryBundle\Updater\VideoGalleryUpdater

services:
    imi_borbas_video_gallery.video_importer_factory:
        class: %imi_borbas_video_gallery.video_importer_factory.class%

    imi_borbas_video_gallery.video_gallery_updater:
        class: %imi_borbas_video_gallery.video_gallery_updater.class%
        arguments: [@imi_borbas_video_gallery.video_importer_factory, @doctrine.orm.entity_manager]
