<?php

namespace ImiBorbas\VideoGalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideoGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoGalleryRepository extends EntityRepository
{
}
