<?php

namespace ImiBorbas\VideoGalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{
    public function deleteFromVideoGalleryExcludingVideoIds($videoGalleryId, array $excludedVideoIds = array())
    {
        $excludedVideoIds[] = '0';
        
        $queryBuilder = $this->createQueryBuilder('v');
        
        $queryBuilder->delete()
                     ->where($queryBuilder->expr()->andX(
                         $queryBuilder->expr()->eq('v.videoGallery', $videoGalleryId),
                         $queryBuilder->expr()->notIn('v.videoId', $excludedVideoIds)
                     ))
                     ->getQuery()
                     ->execute();
    }
}
